#!/bin/bash

create_spring_project() {
    local name=""
    local package=""
    local deps=""

    # Parse argumentos
    while [[ $# -gt 0 ]]; do
        case "$1" in
            -n|--name)
                name="$2"
                shift 2
                ;;
            -p|--package)
                package="$2"
                shift 2
                ;;
            -d|--deps)
                deps="$2"
                shift 2
                ;;
            *)
                echo -e "${CYBER_RED}✘ Opção inválida: $1${RESET}"
                show_spring_new_help
                return 1
                ;;
        esac
    done

    # Validações
    if [[ -z "$name" ]]; then
        echo -e "${CYBER_RED}✘ Nome do projeto é obrigatório${RESET}"
        show_spring_new_help
        return 1
    fi

    if [[ -z "$package" ]]; then
        package="com.example.$name"
    fi

    echo -e "${CYBER_BLUE}▶ Criando projeto Spring Boot: ${name}...${RESET}"
    
    # Implementar integração com Spring Initializr
    local spring_init_url="https://start.spring.io/starter.zip"
    local dependencies="${deps//,/,dependencies=}"
    
    echo -e "${CYBER_BLUE}▶ Baixando projeto do Spring Initializr...${RESET}"
    
    curl -G "$spring_init_url" \
        --data-urlencode "type=maven-project" \
        --data-urlencode "language=java" \
        --data-urlencode "bootVersion=3.2.0" \
        --data-urlencode "baseDir=$name" \
        --data-urlencode "groupId=$package" \
        --data-urlencode "artifactId=$name" \
        --data-urlencode "name=$name" \
        --data-urlencode "description=Spring Boot project generated by ByteBabe" \
        --data-urlencode "packageName=$package" \
        --data-urlencode "dependencies=web,lombok,data-jpa${dependencies}" \
        -o "${name}.zip"

    unzip -q "${name}.zip" && rm "${name}.zip"
    
    # Inicializa configuração do ByteBabe
    cd "$name" && init_spring_config
    
    echo -e "${CYBER_GREEN}✔ Projeto criado com sucesso em: ${CYBER_CYAN}$(pwd)${RESET}"
}
